name: checkpatch review
on: [pull_request]
jobs:
  my_review:
    name: checkpatch review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run checkpatch review
      uses: webispy/checkpatch-action@master

name: Build snapshots
on: [pull_request]
jobs:
  kernelbakery_snapshot:
    uses:  RevolutionPi/ci-workflows/.github/workflows/kernel-snapshot.yml@main
    with:
      kernelbakery_branch: devel/5.10
      picontrol_branch: devel/revpi-5.10
