name: Build
on:
  push:
    branches:
      - devel/revpi-5.10
jobs:
  kernelbakery_snapshot:
    name: snapshot
    uses:  RevolutionPi/ci-workflows/.github/workflows/kernel-snapshot.yml@main
    with:
      kernelbakery_branch: devel/5.10
      picontrol_branch: devel/revpi-5.10
