name: Build snapshots
on:
  pull_request:
    types:
      - labeled
jobs:      
  kernelbakery_snapshot:
    if: ${{ github.event.label.name == 'snapshot-packages' }}
    uses:  RevolutionPi/ci-workflows/.github/workflows/kernel-snapshot.yml@main
    with:
      kernelbakery_branch: devel/5.10
      picontrol_branch: devel/revpi-5.10
