name: Build
on:
  push:
    branches:
      - devel/revpi-5.10
  pull_request:
    types:
      - labeled
jobs:
  kernelbakery_snapshot:
    name: snapshot
    if: ${{ (github.event_name == 'pull_request' && github.event.label.name == 'snapshot-packages') || github.event_name == 'push' }}
    uses:  RevolutionPi/ci-workflows/.github/workflows/kernel-snapshot.yml@main
    with:
      kernelbakery_branch: devel/5.10
      picontrol_branch: devel/revpi-5.10
