name: Build
on:
  push:
    branches:
      - revpi-4.19
  pull_request:
    branches:
      - revpi-4.19
    types:
      - labeled
jobs:
  kernelbakery_snapshot:
    name: snapshot
    if: ${{ (github.event_name == 'pull_request' && github.event.label.name == 'snapshot-packages') || github.event_name == 'push' }}
    uses:  RevolutionPi/ci-workflows/.github/workflows/kernel-snapshot.yml@main
    with:
      kernelbakery_branch: master
      picontrol_branch: master
